working bifurcation submissions with slurm

diff --git a/bifurcation_batch b/bifurcation_batch
--- a/bifurcation_batch
+++ b/bifurcation_batch
@@ -1,15 +1,25 @@
 #!/bin/bash
 
-source $HOME/.bashrc
+if ! [ "$#" -ge "1" ]
+then
+	>&2 echo "usage: $0 parameter-name"
+	exit 1
+fi
 
-ntasks=10
-var="beta_DG"
+source $HOME/.bashrc
+module load anaconda/2.3.0
+source activate TimClusterPython3
+
+
+ntasks=50
+var="$1"
 
 jobname="TSM-Bifurcation-$var"
 output="$jobname-%j.out"
 error="$jobname-%j.err"
+## output="$jobname-%j-%t.out"
+## error="$jobname-%j-%t.err"
 
-mysrun --qos=short --time=0-3 --job-name="$jobname" --output="$output" --error="$error" --ntasks=$ntasks --cpus-per-task=3 bifurcation_single "$var"
-
-# python aws_tsm.py --boundaries both --dg --et --srm --ccs --eddies --num 200 --set-parameter sigma_ET "$sigma_ET*1.e12" dg-et-srm-ccs_pb-sf-bifurc-sigma_ET-${sigma_ET}.out &
+export I_MPI_PMI_LIBRARY=/p/system/slurm/lib/libpmi.so
+mysrun --qos=short --time=0-6 --job-name="$jobname" --output="$output" --error="$error" --ntasks=$ntasks --cpus-per-task=3 bifurcation_single "$var" &
 
